name: Code Check Pipeline
# This is responsible for checking code guidelines with Detekt & Lint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  code_analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'

      - name: Provide RevenueCat Key
        env:
          REVENUECAT_KEY: ${{ secrets.REVENUECAT_KEY }}
        run: echo revenuecat_key=\"$REVENUECAT_KEY\" > ./local.properties

      - name: Run Detekt
        run: |
          ./gradlew --console=plain detekt --stacktrace
      - name: Upload Detekt reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: detekt
          path: ./build/reports/detekt
